# version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    environment:
      - GOOGLE_CREDENTIALS=${GOOGLE_CREDENTIALS}
    env_file:
      - .env
      
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
