services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    buildCommand: ""  # Optional if you need specific build commands
    startCommand: "flask run --host=0.0.0.0 --port=5001"
    autoDeploy: true
    envVars:
      - key: GOOGLE_CREDENTIALS
        sync: false  # Sync to true if defined in Render's environment
    # envFilePath: .env

  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: "npm install && npm run build"
    startCommand: "serve -s build -l 80"
    autoDeploy: true
