services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    buildCommand: ""  # Optional if you need specific build commands
    startCommand: "flask run --host=0.0.0.0 --port=5000"
    autoDeploy: true
    # envVars:
    #   - key: GOOGLE_CREDENTIALS
    #     sync: false  # You can set this to true if you have defined GOOGLE_CREDENTIALS in Render's environment
    # envFilePath: .env
    routes:
      - type: http
        source: /
        targetPort: 5000
    mounts:
      - type: volume
        name: backend-volume
        path: /app

  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: "npm install && npm run build"
    startCommand: "serve -s build -l 80"
    autoDeploy: true
    routes:
      - type: http
        source: /
        targetPort: 80
    mounts:
      - type: volume
        name: frontend-volume
        path: /app
